### ISSUE TITLE
SPARK: GNAT2Why issue.

### ISSUE THREAD

**Issue by Blady-Com** [steve-cs/gnat-builder#12] opened 2020-02-17 11:44 UTC
Hello,
When building SPARK, I've got this issue:
gprbuild  -Pgnat2why -j0 -cargs  -largs 
–	osint.adb:2186:28: "To_C" is undefined
–	osint.adb:2208:17: "To_Ada" is undefined
A patch has been set:
https://github.com/gcc-mirror/gcc/commit/25a0f9cfaeca20baeaaa0c76911821949aadcb40
HTH, Pascal.

**Comment by steve-cs** [comment] 2020-02-17 20:56
Spark FSF branch depends GCC trunk.  SPARK 19.x should build cleanly against the latest GCC 9.x release.  I believe that SPARK 20.x should build against future GCC 10.x releases.  For now that means GCC trunk/master.

My nightly builds are SPARK fsf branch against GCC master.  So I don't see this issue.

**Comment by Blady-Com** [comment] 2020-02-19 20:00
Hello Steve, I needs SPARK 20.x for some recent improvements.
Could you consider testing the patch on your configuration?
If ok the change would then fit both configurations?
Thanks, Pascal.

**Comment by steve-cs** [comment] 2020-02-19 21:02
OK, now I see.  Getting 20.x to build is a reasonable ask.  Reopening ...

My copy of gnat_src is rather stale.  My last sync was Sept 22 and the patch you're interested was was done Sept 26.  Let me update gnat_src from gcc/master and see where the fsf, master and 20.2 branches stand.

**Comment by steve-cs** [comment] 2020-02-20 02:40
Unable to reproduce your problem building SPARK 20.2 with gcc version 10.0.1 20200211 (experimental) (GCC).  I can build spark/fsf and spark/20.2 branches without complaint. spark/master is currently out of sync with FSF gcc compilers.  Nevertheless, I did update the GNAT source repository from gcc/master to make it current including the specific patch you requested.  I'm not optimistic that that will fix your problem.  I suspect some other compiler or environment issue on your side.

**Comment by Blady-Com** [comment] 2020-02-21 12:34
Thanks Steve, it's ok now on my side.

**Comment by steve-cs** [comment] 2020-02-21 20:56
Great.  FYI, the whole set of 20.2 branches builds fine for me with the exception of GPS which complains about some implicit conversions that recent compiler changes in 10.0.x no longer allow.  This has already been fixed in GPS/master.

**Closed as completed by steve-cs** 2020-02-21 20:56 UTC
